"""Physics-Anchored Digital Twin for Aero-Piston Engine.

Models a generic 4-cylinder, 4-stroke, turbocharged aero-piston engine.
Calculates thermodynamic states, energy balances, lubrication hydrodynamics,
and vibration harmonics to produce expected nominal sensor values under dynamic flight regimes.
"""

import math
from dataclasses import dataclass
from typing import Dict, Any, Optional
from aeris.config.engine_specs import EngineParameters

@dataclass
class TwinPrediction:
    """Expected sensor values generated by the physical digital twin."""
    egt_c: float
    cht_c: float
    oil_pressure_bar: float
    oil_temp_c: float
    fuel_flow_lph: float
    vibration_mms: float
    engine_efficiency: float
    manifold_pressure_inhg: float
    air_density_kgm3: float
    brake_power_kw: float

class AeroPistonTwin:
    """Dynamic physics model of a 4-stroke turbocharged aero-piston engine."""

    def __init__(self, params: Optional[EngineParameters] = None):
        self.params = params or EngineParameters()
        
        # State variables for dynamic thermal inertia
        self._current_cht: float = 105.0
        self._current_oil_temp: float = 90.0
        self._initialized: bool = False

    def reset(self):
        """Reset internal dynamic thermal states."""
        self._current_cht = 105.0
        self._current_oil_temp = 90.0
        self._initialized = False

    @staticmethod
    def atmospheric_model(altitude_m: float, ambient_temp_c: float) -> Dict[str, float]:
        """Calculates atmospheric pressure, temperature lapse, and air density (ISA variant)."""
        # Gas constants
        g0 = 9.80665      # m/s^2
        R = 287.05        # J/(kg*K)
        L = 0.0065        # K/m lapse rate
        T0 = 288.15       # Sea level standard temp (15 C)
        P0 = 101325.0     # Sea level standard pressure (Pa)

        # Actual ambient temperature in Kelvin
        T_kelvin = ambient_temp_c + 273.15
        
        # Pressure calculation using barometric formula
        # Clamp altitude between 0 and 10000 meters (~33,000 ft)
        alt = max(0.0, min(10000.0, altitude_m))
        P_ambient = P0 * math.pow(max(0.1, 1.0 - (L * alt) / T0), (g0 / (R * L)))
        
        # Density rho = P / (R * T)
        density = P_ambient / (R * max(200.0, T_kelvin))
        
        return {
            "pressure_pa": P_ambient,
            "pressure_inhg": P_ambient / 3386.39,
            "density_kgm3": density,
            "density_ratio": density / 1.225
        }

    def predict(
        self,
        rpm: float,
        throttle: float,
        altitude_m: float = 1500.0,
        ambient_temp_c: float = 20.0,
        engine_load: Optional[float] = None,
        dt_seconds: float = 1.0
    ) -> TwinPrediction:
        """Predict nominal expected sensor values given operational state.

        Args:
            rpm: Engine speed in revolutions per minute (1400 - 5800)
            throttle: Throttle position [0.0 (idle) to 1.0 (full)]
            altitude_m: Operational altitude in meters
            ambient_temp_c: Outside ambient air temperature in Celsius
            engine_load: Engine load factor [0.0 - 1.0]. If None, inferred from RPM & throttle.
            dt_seconds: Time delta for thermal integration
        """
        # Constrain inputs
        rpm = max(1200.0, min(6200.0, float(rpm)))
        throttle = max(0.0, min(1.0, float(throttle)))
        ambient_temp_c = max(-50.0, min(60.0, float(ambient_temp_c)))
        
        # Atmosphere
        atmo = self.atmospheric_model(altitude_m, ambient_temp_c)
        rho_ratio = atmo["density_ratio"]
        ambient_press_inhg = atmo["pressure_inhg"]

        # 1. Turbocharger & Manifold Air Pressure (MAP)
        # Turbo maintains up to ~38 inHg at WOT up to critical altitude (~4500m)
        turbo_boost_cap = min(self.params.turbo_boost_max_inhg, ambient_press_inhg * 1.65)
        # MAP depends on throttle and turbo boost
        map_inhg = ambient_press_inhg + throttle * (turbo_boost_cap - ambient_press_inhg)
        map_inhg = max(12.0, min(39.0, map_inhg))

        # 2. Engine Load and Volumetric Efficiency
        if engine_load is None:
            # Theoretical load is proportional to MAP and RPM ratio
            rpm_ratio = rpm / self.params.max_rpm
            engine_load = max(0.15, min(1.0, 0.2 + 0.8 * throttle * (rpm_ratio ** 0.8)))
        else:
            engine_load = max(0.1, min(1.0, float(engine_load)))

        # Volumetric efficiency curve (peaks around nominal cruise RPM 5000)
        rpm_norm = rpm / self.params.nominal_cruise_rpm
        vol_eff = 0.88 * math.exp(-0.5 * ((rpm_norm - 1.0) / 0.35) ** 2)

        # 3. Brake Power Calculation (kW)
        # Displacement in m^3: 1211 cc = 0.001211 m^3
        v_disp = self.params.displacement_cc * 1e-6
        # Mass air flow: m_dot_air = (rho * V_disp * (RPM/120)) * vol_eff
        m_dot_air = (atmo["density_kgm3"] * (map_inhg / max(15.0, ambient_press_inhg))) * v_disp * (rpm / 120.0) * vol_eff
        
        # Stoichiometric / Enriched Air-Fuel Ratio (A/F ~ 12.5 at WOT to 14.7 at cruise)
        afr = 14.7 - 2.0 * throttle
        m_dot_fuel_kg_s = m_dot_air / max(10.0, afr)
        
        # Fuel flow in Liters/hour (density of AVGAS/MOGAS ~ 0.73 kg/L)
        fuel_flow_lph = max(6.0, (m_dot_fuel_kg_s * 3600.0) / 0.73)

        # Brake Power = Fuel Energy * Thermal Efficiency
        lhv_fuel_kj_kg = 43500.0  # Lower Heating Value of gasoline in kJ/kg
        fuel_power_kw = m_dot_fuel_kg_s * lhv_fuel_kj_kg
        
        # Indicated thermal efficiency: 32% - 37%
        thermal_eff = 0.34 * (1.0 - 0.08 * (1.0 - engine_load))
        # Friction mean effective pressure increases with RPM
        mech_eff = 0.88 - 0.12 * ((rpm / self.params.max_rpm) ** 1.5)
        engine_efficiency = max(0.20, min(0.35, thermal_eff * mech_eff))
        brake_power_kw = fuel_power_kw * engine_efficiency

        # 4. Exhaust Gas Temperature (EGT)
        # Energy partition: ~35% exhaust, ~30% cooling/oil, ~35% work
        # Base EGT at cruise is ~720°C, increasing with load and leaning, decreasing with altitude if rich
        base_egt = 650.0 + (engine_load * 90.0) + ((1.0 - throttle) * 30.0)
        # Ambient temp effect on inlet air
        ambient_egt_delta = 0.4 * (ambient_temp_c - 15.0)
        # Richness reduction at full power:
        power_enrichment = -25.0 * (1.0 if throttle > 0.85 else 0.0)
        target_egt = base_egt + ambient_egt_delta + power_enrichment
        target_egt = max(580.0, min(840.0, target_egt))

        # 5. Cylinder Head Temperature (CHT) with dynamic lag
        # Steady-state target CHT is heat input from combustion vs cooling airflow
        # Coolant/fin heat sink settled temperature:
        cooling_factor = math.sqrt(max(0.4, rho_ratio)) # Ram air cooling density effect
        steady_cht = ambient_temp_c + (16.0 + 85.0 * engine_load) / cooling_factor
        steady_cht = max(65.0, min(138.0, steady_cht))

        # 6. Lubrication Circuit: Oil Temperature and Oil Pressure
        # Steady-state oil temp follows engine heat and oil cooler capacity
        steady_oil_temp = ambient_temp_c + (20.0 + 68.0 * engine_load)
        steady_oil_temp = max(60.0, min(120.0, steady_oil_temp))

        # First-order thermal lag integration
        if not self._initialized:
            self._current_cht = steady_cht
            self._current_oil_temp = steady_oil_temp
            self._initialized = True
        else:
            tau_cht = 10.0   # seconds thermal time constant
            tau_oil = 30.0   # seconds thermal time constant for oil volume
            alpha_cht = 1.0 - math.exp(-dt_seconds / tau_cht)
            alpha_oil = 1.0 - math.exp(-dt_seconds / tau_oil)
            self._current_cht += alpha_cht * (steady_cht - self._current_cht)
            self._current_oil_temp += alpha_oil * (steady_oil_temp - self._current_oil_temp)

        # Oil Pressure: Gear pump delivers flow proportional to RPM.
        # Oil viscosity drops with higher oil temperature:
        # P_oil = base_pressure * (RPM / nominal_RPM) * (1 - temp_viscosity_drop)
        viscosity_factor = 1.0 - 0.006 * (self._current_oil_temp - 85.0)
        viscosity_factor = max(0.65, min(1.35, viscosity_factor))
        rpm_factor = math.sqrt(rpm / self.params.nominal_cruise_rpm)
        oil_pressure_bar = 4.2 * rpm_factor * viscosity_factor
        # Relief valve limits max pressure to ~5.2 bar
        oil_pressure_bar = max(1.8, min(5.4, oil_pressure_bar))

        # 7. Engine Vibration (mm/s RMS)
        # Baseline vibration consists of rotational unbalance (1x RPM) + combustion firings (2x RPM)
        # Increases with torque/load and engine speed
        vib_speed_term = 0.8 * (rpm / self.params.nominal_cruise_rpm) ** 1.2
        vib_load_term = 0.6 * engine_load
        vibration_mms = max(0.6, vib_speed_term + vib_load_term)

        return TwinPrediction(
            egt_c=round(target_egt, 2),
            cht_c=round(self._current_cht, 2),
            oil_pressure_bar=round(oil_pressure_bar, 3),
            oil_temp_c=round(self._current_oil_temp, 2),
            fuel_flow_lph=round(fuel_flow_lph, 2),
            vibration_mms=round(vibration_mms, 2),
            engine_efficiency=round(engine_efficiency, 4),
            manifold_pressure_inhg=round(map_inhg, 2),
            air_density_kgm3=round(atmo["density_kgm3"], 4),
            brake_power_kw=round(brake_power_kw, 2)
        )
